### ISSUE TITLE
[fetch] replicator_nodeのログ出力が多すぎてデバッグがしづらい

### ISSUE THREAD

**Issue by 708yamaguchi** [knorth55/jsk_robot#234]
fetchを使っていると、以下のようなエラーを大量に吐かれることがあって、デバッグがしづらいです。

```
[ERROR] [1653231340.987602] [/replicator_node:rosout]: [mongorestore] - E11000 duplicate key error collection: jsk_robot_lifelog.fetch1075 index: _id_ dup key: { : ObjectId('6243af9651998d10f0c7787c') }
```

エラーを吐いているのは以下の部分だと思うのですが、エラーは直るものでしょうか？
もし直らないなら、エラーの頻度を下げる、logger levelを上げる、ログファイルを分ける、などの対策が考えられるのですが、どうしましょうか。
https://github.com/strands-project/mongodb_store/blob/00efed6ac81dc3909819d76073d424d18567ecae/mongodb_store/scripts/replicator_node.py#L128-L129

cc @knorth55 @mqcmd196 @tkmtnt7000

**Comment by 708yamaguchi** [comment]
大日方くん、お手伝いありがとうございました。

**Comment by knorth55** [comment]
throttleのすればいいと思います
で根本的な解決としてはそこではないよね、って話です

**Comment by 708yamaguchi** [comment]
> throttleのすればいいと思います
> で根本的な解決としてはそこではないよね、って話です

はい、僕もそうだと考えています。
まずは対症療法としてthrottleを追加したプルリクエストを出します。
根本解決のため、引き続きデバッグをしたいと思います

**Comment by 708yamaguchi** [comment]
一旦https://github.com/knorth55/jsk_robot/pull/237 で様子を見ます

不具合があればまたプルリクエストを出します
