### ISSUE TITLE
[fetch] supervisorのジョブが正しく起動しないときがある

### ISSUE THREAD

**Issue by 708yamaguchi** [knorth55/jsk_robot#235]
以下のように、supervisorのjobの大半が死ぬことがあります。
今朝はキッチンデモが起動しませんでした。

ログを見ると、以下のようにネットワーク関連のエラーが発生していそうです。

```bash
$ sudo less -R /var/log/ros/jsk-log-wifi.log
unable to set ROS_IP and ROS_HOSTNAME
```

```bash
$ sudo less -R /var/log/ros/jsk-fetch-startup.log
waiting for roscore to come up
ERROR: Unable to communicate with master!
ERROR: Unable to communicate with master!
unable to set ROS_IP and ROS_HOSTNAME
```

エラーは以下のrossetipだと思っています。
まだ検証できていないのですが、wlan1などのネットワークインターフェースが割り当てられる前にrossetipコマンドを叩くと上記のエラーが出る気がしています。

```
if [ -e /var/lib/robot/config.bash ];then . /var/lib/robot/config.bash ;fi && rossetip $NETWORK_DEFAULT_ROS_INTERFACE
```
https://github.com/knorth55/jsk_robot/blob/fetch15/jsk_fetch_robot/jsk_fetch_startup/supervisor_scripts/jsk-log-wifi.conf

rossetipの定義
https://github.com/jsk-ros-pkg/jsk_common/blob/7721ebd547e521bbe63fa20579185f00f29fb4f2/jsk_tools/env-hooks/99.jsk_tools.sh#L103-L126

@sktometometo 
理想的には、config.bashの中でwlan1などが振られるまで待つのがいいのかなとおもうのですが、どうでしょうか。
そちらでも原因を調べてもらえると助かります。
ちなみにfetch15ではこの問題は発生していません。

cc @knorth55 @mqcmd196 @tkmtnt7000

![log-wifi](https://user-images.githubusercontent.com/19769486/169730317-e6dc936d-0ee3-4a6b-87f9-568247e82df6.png)

**Comment by 708yamaguchi** [comment]
大日方くん、お手伝いありがとうございました。

**Comment by knorth55** [comment]
rossetipに起動するinterfaceを指定できるようにするとか、どうでしょうか

**Comment by sktometometo** [comment]
Network Interfaceが存在しないとき&IPアドレスがまだ設定されていないときになるので、NETWORK_DEFAULT_ROS_INTERACEをipアドレスに設定しておくと治ります。

**Comment by 708yamaguchi** [comment]
closed this as completedになっているけど、

> NETWORK_DEFAULT_ROS_INTERACEをipアドレスに設定しておくと治ります。

というのがconfig.bashを書き直すことだとしたら、プルリクエストを出さないといけない？

**Comment by sktometometo** [comment]
jsk_fetch_startup/config/config.bash 以下にあるものはどちらにせよ書き換えられる前提でおいてあるのと、ケースによっては動くのでそのままでもいいかなと思ってる。README.md の NETWORK_DEFAULT_ROS_INTERFACE の説明の修正のPRは出す。

**Comment by sktometometo** [comment]
@708yamaguchi あと、この類のIssueは jsk-ros-pkg/jsk_robot の方に出そうという話だったと思うのでそちらに出そう.

**Comment by 708yamaguchi** [comment]
jsk-ros-pkgにプルリクエストが送られていないので、こちらに書きました。
https://github.com/knorth55/jsk_robot/pull/228

**Comment by 708yamaguchi** [comment]
先ほどのデバッグメモ

最近の変更で、supervisorのジョブを起動する前にrossetipコマンドを使用していたのですが、その影響でROS_HOSTNAMEという環境変数がセットされるようになりました。
https://github.com/jsk-ros-pkg/jsk_common/blob/30cdff0624b253d58af2b00ccdf0277cf27d9ec1/jsk_tools/env-hooks/99.jsk_tools.sh#L113

その影響で、mongodb_store_inc.launchのmongodb_hostのアドレスが、localhostから133.11.216.218に変更されました。
https://github.com/strands-project/mongodb_store/blob/00efed6ac81dc3909819d76073d424d18567ecae/mongodb_store/launch/mongodb_store_inc.launch#L32

mongodbのbind_ipの設定により、127.0.0.1以外からの接続を受け付けていなかったため、接続できないというエラーが起きていました。
今はbind_ipを0.0.0.0として全てのIPアドレスからの接続を許可するようにしたため、エラーが起きなくなりました
https://gitlab.jsk.imi.i.u-tokyo.ac.jp/fetch/fetch1075_etc_melodic/-/commit/e86cf9ee900830a95653f29078c941190edb98e7

**Comment by sktometometo** [comment]
@708yamaguchi PRがどこに出されているかに関わらず、fork先にissueを立てると検索しづらいのとknorth55の管理が消えたときに話が消滅するので、fork元にissueを立てたほうがいいと思う。

**Comment by sktometometo** [comment]
jsk-ros-pkg/master の話と knorth55/fetch15  の話がごちゃごちゃになる問題はあるけど、ラベルなりタグなりで分ければいいような。実機のラベル付けるissueはそもそも knorth55/fetch15 の話だろうし。

**Comment by 708yamaguchi** [comment]
新城は全部jsk-ros-pkgにプルリク出して、
山口は全部jsk-ros-pkgにイシュー立てる
にしましょう
