### ISSUE TITLE
キッチンデモの途中にedgetpu_object_detectorの結果が切り替わり、rosbagに保存されない

### ISSUE THREAD

**Issue by iory** [knorth55/jsk_robot#285]
https://github.com/knorth55/jsk_robot/pull/277
おそらくこのPRが原因だと思うのですが、キッチンデモの途中にedgetpu_object_detectorの結果が切り替わり、rosbagに保存されないという問題がキッチンデモで起きました。

デモ終了後に届いたメールを添付します。
go_to_kitchen_object_detection.mp4: https://drive.google.com/uc?id=1W5H37XHYlrTkUF6fYqLgdqxV-MjYwe-s
の動画が途中で切れています。

@sktometometo こちら対応いただけますか？

```
Hi,
I succeeded in doing Go to kitchen.
I succeeded to upload data.

go_to_kitchen_result.yaml: https://drive.google.com/uc?id=1YeuxxxdsakMtvYbjBPUgPzK2apZpOMRL
go_to_kitchen_head_camera.mp4: https://drive.google.com/uc?id=1rVp7q6x2P3ojBw8ytBDzJg60g2sIkfQ8
go_to_kitchen_object_detection.mp4: https://drive.google.com/uc?id=1W5H37XHYlrTkUF6fYqLgdqxV-MjYwe-s
go_to_kitchen_panorama.mp4: https://drive.google.com/uc?id=1S6-Nay0s7DBSmqxRsdclCOeH8BH7k4J_
go_to_kitchen_rviz.mp4: https://drive.google.com/uc?id=1vFRxKoy6nCGaiHgBHZ0-hhRQ-e60O1gO
go_to_kitchen_audio.wav: https://drive.google.com/uc?id=19G6V3qqwCwbDN4VjfCne845rVcl4-byd
go_to_kitchen_rosbag.bag: https://drive.google.com/uc?id=1UDUUvchSP83xo5qKgZpwB1-aqbfnPJhu
trashcan_inside.jpg: https://drive.google.com/uc?id=1y6MlxJsMYUMHE2epzgESokoVXny3N8bn

Following smach is reported.
 - At 2022-07-05T23:48:55, Active states is REPORT-START-GO-TO-KITCHEN.
 - At 2022-07-05T23:48:57, Active states is GET-LIGHT-ON.
 - At 2022-07-05T23:48:58, Active states is REPORT-LIGHT-ON.
 - At 2022-07-05T23:49:00, Active states is MOVE-TO-SINK-FRONT.
 - At 2022-07-05T23:49:26, Active states is INSPECT-KITCHEN.
 - At 2022-07-05T23:49:46, Active states is MOVE-TO-TRASHCAN-FRONT.
 - At 2022-07-05T23:49:54, Active states is INSPECT-TRASHCAN.
 - At 2022-07-05T23:50:19, Active states is AUTO-DOCK.
 - At 2022-07-05T23:51:02, Active states is ROOM-LIGHT-OFF.
 - At 2022-07-05T23:51:02, Active states is FINISH.

Following object recognition is reported.
 - At 2022-07-05T23:49:46, (cup) is found in kitchen sink.```
 -

**Comment by knorth55** [comment]
`edgetpu_manager`で全てのdetector, estimatorに切り替えられるようにしておくのがいいかもしれません．
そうすれば`edgetpu_object_detector`と`edgetpu_panorama_object_detector`が両方動かすことができると思います．
`edgetpu_human_pose_estimator` -> `edgetpu_panorama_object_detector`に切り替えればいいのかな．

**Comment by 708yamaguchi** [comment]
fetchの起動時は2つのedgetpuで
・edgetpu_object_detector
・edgetpu_human_pose_estimator
が立ち上がっています。

北川さんの提案だと
・edgetpu_object_detector
・edgetpu_panorama_object_detector
になるということですよね。
これでデモ中にedgetpu_object_detectorが途切れることはなくなると思うので、良い機能だと思います。

個人的な意見としては、北川さんの作戦をもってしてもデフォルト機能（今回でいうedgetpu_human_pose_estimator）を使いたい人がいたら混乱してしまうと思います。
以下の2つが対策でしょうか。
・edgetpuの種類を切り替えたら使用後に元に戻すことを徹底する
・edgetpuの機能として、一定期間subscribeされなかったらデフォルトの認識器に戻すようにする

**Comment by knorth55** [comment]
> ・edgetpuの種類を切り替えたら使用後に元に戻すことを徹底する

これを前提で書いていました．

**Comment by sktometometo** [comment]
リソース管理システムが無いと解消できない類の問題で今解消する気が無いのでbeg_to_personをdisableにします。

**Comment by sktometometo** [comment]
https://github.com/sktometometo/ros_lock
こいつの良い適用例になるとは思うけど先に論文書くので後回しかな...

**Comment by sktometometo** [comment]
https://github.com/knorth55/jsk_robot/pull/287 一旦revertしました。
